# FUNDING ANALYSIS FOR INDIAN STARTUPS

#### Team: Team Namibia

## Table of Contents


- [Business Understanding](#Business-Understanding)

- [Data Understanding](#data-understanding)
    - [Data Collection](#data-collection)
    - [Feature Description](#feature-description)
    - [Viewing the data](#viewing-the-data)
    - [Data Quality Assessment](#data-quality-assessment)

- [Data Preparation](#data-preparation)
    - [Data Cleaning](#data-cleaning)
    - [Exploratory Data Analysis](#exploratory-data-analysis)



## Business Understanding
Team Namibia aims to venture into the start-up space in India and being the data expert of the team, we've have been tasked with investigating the econmoic landscape and coming out with a course of action for this endeavour.


#### Problem Statement:
Investigating the dynamics of startup funding in India over the period from 2018 to 2021. The aim is to understand the trends, sector preferences, investment stages, key investors, and geographical distribution of the funding. Additionally, if there have been significant differences in funding amounts across different years and sectors, it can guide the action plan to be taken.

#### Objective
The goal of this analysis is to provide insights into the startup funding landscape in India from 2018 to 2021. 
- Identify trends and patterns in funding amounts over the years.
- Determine which sectors received the most funding and how sector preferences changed over time.
- Understand the distribution of funding across different stages of startups (e.g., Seed, Series A).
- Identify key investors and their investment behaviors.
- Analyze the geographical distribution of funding within India.

#### Analytical Questions
1. What are the trends and patterns in funding amounts for startups in India beetween 2018 to 2021?
   - Analyzing the annual and quarterly trends in funding can reveal patterns and growth trajectories. Look for peaks, dips, and any consistent growth patterns over these years.
2. Which sectors received the most funding, and how did sector preferences change over time from 2018 to 2021?
   - Identifying which industries or sectors received the most funding can show sectoral preferences and shifts. Understanding how this distribution has evolved over the years can highlight emerging trends and declining interests.
3. How is the distribution of funding across different stages of startups (e.g., Seed, Series A)?
   - Analyzing the funding amounts at different startup stages can provide insights into the investment appetite at various growth phases. It can also help in understanding the maturity and risk preference of investors.
4. Who are the key investors in Indian startups, and what are their investment behaviors/patterns?
   - Identifying the most active investors and analyzing their investment portfolios can shed light on key players in the ecosystem. Understanding their investment patterns can also reveal strategic preferences and alliances.
5. What is the geographical distribution of startup funding within India, and how has this distribution changed over the years 2018 to 2021?
   - Analyzing the geographical distribution of startup funding can show regional hotspots for entrepreneurship and investment. Observing how this has changed over the years can reveal shifts in regional focus and development.



### Null Hypothesis (H0)
There is no significant difference in the funding amounts for startups in India between the years 2018 and 2021 across different sectors.

### Alternate Hypothesis (H1)
There is a significant difference in the funding amounts for startups in India between the years 2018 and 2021 across different sectors.

### Importing the necessary packages

In [83]:
# Import the pyodbc library to handle ODBC database connections
import pyodbc 

# Import the dotenv function to load environment variables from a .env file
from dotenv import dotenv_values 

# Import the pandas and numpy library for data manipulation and analysis
import pandas as pd 
import numpy as np


# Importing Matplotlib for  visualizations in Python
import matplotlib.pyplot as plt

# Importing Seaborn for statistical data visualization based on Matplotlib
import seaborn as sns


# Import the warnings library to handle warning messages
import warnings

# Filter out (ignore) any warnings that are raised
warnings.filterwarnings('ignore')

 ### Establishing a connection to the database

In [14]:
# Load environment variables from .env file into a dictionary
environment_variables = dotenv_values('.env')

# Get the values for the credentials you set in the .env file
database = environment_variables.get("DATABASE")
server = environment_variables.get("SERVER")
username = environment_variables.get("UID")
password = environment_variables.get("PWD")

# Create the connection string using the retrieved credentials
connection_string = f"DRIVER={{SQL Server}};SERVER={server};DATABASE={database};UID={username};PWD={password};MARS_Connection=yes;MinProtocolVersion=TLSv1.2;"

In [15]:
# Establish a connection to the database using the connection string
connection = pyodbc.connect(connection_string)

In [16]:
# Define the SQL query to select all columns from the specified table
query = "Select * from dbo.LP1_startup_funding2020"

# Execute the SQL query and fetch the result into a pandas DataFrame using the established database connection
data1 = pd.read_sql(query, connection)

data1

,Company_Brand,Founded,HeadQuarter,Sector,What_it_does,Founders,Investor,Amount,Stage,column10
0,Aqgromalin,2019.0,Chennai,AgriTech,Cultivating Ideas for Profit,"Prasanna Manogaran, Bharani C L",Angel investors,200000.0,None,None
1,Krayonnz,2019.0,Bangalore,EdTech,An academy-guardian-scholar centric ecosystem ...,"Saurabh Dixit, Gurudutt Upadhyay",GSF Accelerator,100000.0,Pre-seed,None
2,PadCare Labs,2018.0,Pune,Hygiene management,Converting bio-hazardous waste to harmless waste,Ajinkya Dhariya,Venture Center,NaN,Pre-seed,None
3,NCOME,2020.0,New Delhi,Escrow,Escrow-as-a-service platform,Ritesh Tiwari,"Venture Catalysts, PointOne Capital",400000.0,None,None
4,Gramophone,2016.0,Indore,AgriTech,Gramophone is an AgTech platform enabling acce...,"Ashish Rajan Singh, Harshit Gupta, Nishant Mah...","Siana Capital Management, Info Edge",340000.0,None,None
...,...,...,...,...,...,...,...,...,...,...
1050,Leverage Edu,NaN,Delhi,Edtech,AI enabled marketplace that provides career gu...,Akshay Chaturvedi,"DSG Consumer Partners, Blume Ventures",1500000.0,None,None
1051,EpiFi,NaN,None,Fintech,It offers customers with a single interface fo...,"Sujith Narayanan, Sumit Gwalani","Sequoia India, Ribbit Capital",13200000.0,Seed Round,None
1052,Purplle,2012.0,Mumbai,Cosmetics,Online makeup and beauty products retailer,"Manish Taneja, Rahul Dash",Verlinvest,8000000.0,None,None
1053,Shuttl,2015.0,Delhi,Transport,App based bus aggregator serice,"Amit Singh, Deepanshu Malviya",SIG Global India Fund LLP.,8043000.0,Series C,None
1054,Pando,2017.0,Chennai,Logitech,Networked logistics management software,"Jayakrishnan, Abhijeet Manohar",Chiratae Ventures,9000000.0,Series A,None

In [17]:
# Define the SQL query to select all columns from the specified table
query = "Select * from dbo.LP1_startup_funding2021"

# Execute the SQL query and fetch the result into a pandas DataFrame using the established database connection
data2 = pd.read_sql(query, connection)

data2

,Company_Brand,Founded,HeadQuarter,Sector,What_it_does,Founders,Investor,Amount,Stage
0,Unbox Robotics,2019.0,Bangalore,AI startup,Unbox Robotics builds on-demand AI-driven ware...,"Pramod Ghadge, Shahid Memon","BEENEXT, Entrepreneur First","$1,200,000",Pre-series A
1,upGrad,2015.0,Mumbai,EdTech,UpGrad is an online higher education platform.,"Mayank Kumar, Phalgun Kompalli, Ravijot Chugh,...","Unilazer Ventures, IIFL Asset Management","$120,000,000",None
2,Lead School,2012.0,Mumbai,EdTech,LEAD School offers technology based school tra...,"Smita Deorah, Sumeet Mehta","GSV Ventures, Westbridge Capital","$30,000,000",Series D
3,Bizongo,2015.0,Mumbai,B2B E-commerce,Bizongo is a business-to-business online marke...,"Aniket Deb, Ankit Tomar, Sachin Agrawal","CDC Group, IDG Capital","$51,000,000",Series C
4,FypMoney,2021.0,Gurugram,FinTech,"FypMoney is Digital NEO Bank for Teenagers, em...",Kapil Banwari,"Liberatha Kallat, Mukesh Yadav, Dinesh Nagpal","$2,000,000",Seed
...,...,...,...,...,...,...,...,...,...
1204,Gigforce,2019.0,Gurugram,Staffing & Recruiting,A gig/on-demand staffing company.,"Chirag Mittal, Anirudh Syal",Endiya Partners,$3000000,Pre-series A
1205,Vahdam,2015.0,New Delhi,Food & Beverages,VAHDAM is among the world’s first vertically i...,Bala Sarda,IIFL AMC,$20000000,Series D
1206,Leap Finance,2019.0,Bangalore,Financial Services,International education loans for high potenti...,"Arnav Kumar, Vaibhav Singh",Owl Ventures,$55000000,Series C
1207,CollegeDekho,2015.0,Gurugram,EdTech,"Collegedekho.com is Student’s Partner, Friend ...",Ruchir Arora,"Winter Capital, ETS, Man Capital",$26000000,Series B
1208,WeRize,2019.0,Bangalore,Financial Services,India’s first socially distributed full stack ...,"Vishal Chopra, Himanshu Gupta","3one4 Capital, Kalaari Capital",$8000000,Series A

In [20]:
# Write the concatenated DataFrame 'df' to a CSV file named 'lp1.csv'
data1.to_csv('startup_funding2020.csv')
data2.to_csv('startup_funding2021.csv')

In [18]:
# Concatenate two DataFrames 'data1' and 'data2' vertically (along the rows)
df = pd.concat([data1, data2])

# Write the concatenated DataFrame 'df' to a CSV file named 'lp1.csv'
df.to_csv('lp1.csv')

# Read the CSV file into a DataFrame
lp1 = pd.read_csv('lp1.csv')

lp1.head(10)

,Unnamed: 0,Company_Brand,Founded,HeadQuarter,Sector,What_it_does,Founders,Investor,Amount,Stage,column10
0,0,Aqgromalin,2019.0,Chennai,AgriTech,Cultivating Ideas for Profit,"Prasanna Manogaran, Bharani C L",Angel investors,200000.0,NaN,NaN
1,1,Krayonnz,2019.0,Bangalore,EdTech,An academy-guardian-scholar centric ecosystem ...,"Saurabh Dixit, Gurudutt Upadhyay",GSF Accelerator,100000.0,Pre-seed,NaN
2,2,PadCare Labs,2018.0,Pune,Hygiene management,Converting bio-hazardous waste to harmless waste,Ajinkya Dhariya,Venture Center,NaN,Pre-seed,NaN
3,3,NCOME,2020.0,New Delhi,Escrow,Escrow-as-a-service platform,Ritesh Tiwari,"Venture Catalysts, PointOne Capital",400000.0,NaN,NaN
4,4,Gramophone,2016.0,Indore,AgriTech,Gramophone is an AgTech platform enabling acce...,"Ashish Rajan Singh, Harshit Gupta, Nishant Mah...","Siana Capital Management, Info Edge",340000.0,NaN,NaN
5,5,qZense,2019.0,Bangalore,AgriTech,qZense Labs is building the next-generation Io...,"Rubal Chib, Dr Srishti Batra","Venture Catalysts, 9Unicorns Accelerator Fund",600000.0,Seed,NaN
6,6,MyClassboard,2008.0,Hyderabad,EdTech,MyClassboard is a full-fledged School / Colleg...,Ajay Sakhamuri,ICICI Bank.,600000.0,Pre-series A,NaN
7,7,Metvy,2018.0,Gurgaon,Networking platform,AI driven networking platform for individuals ...,Shawrya Mehrotra,HostelFund,NaN,Pre-series,NaN
8,8,Rupeek,2015.0,Bangalore,FinTech,Rupeek is an online lending platform that spec...,"Amar Prabhu, Ashwin Soni, Sumit Maniyar","KB Investment, Bertelsmann India Investments",45000000.0,Series C,NaN
9,9,Gig India,2017.0,Pune,Crowdsourcing,GigIndia is a marketplace that provides on-dem...,"Aditya Shirole, Sahil Sharma","Shantanu Deshpande, Subramaniam Ramadorai",1000000.0,Pre-series A,NaN

In [19]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1055 entries, 0 to 1054
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Company_Brand  1055 non-null   object
 1   Founded        842 non-null    float64
 2   HeadQuarter    961 non-null    object
 3   Sector         1042 non-null   object
 4   What_it_does   1055 non-null   object
 5   Founders       1043 non-null   object
 6   Investor       1017 non-null   object
 7   Amount         801 non-null    float64
 8   Stage          591 non-null    object
 9   column10       2 non-null      object
dtypes: float64(2), object(8)
memory usage: 82.5+ KB

[Back to Top](#Table-of-Contents)


# Data Understanding

In this section, we seek to undestand the data that will help us solve our business problem/question. We detail how the briefly mention how the data was collected, we describe the useful features within the dataset, assess our data through an exploratory data analysis and then conclude with a data quality assessment

### Data Collection
The analysis for the Indian startup funding covers a span of 4 years and the data on each of the years comes via a unique dataset in a csv format. 
- Two of the datasets (2020 and 2021) were obtained from the sakila dataset online. The 2020 dataset was saved to a variable data1 whilst the 2021 dataset was saved to data2.
- The dataset for the year 2019 is a  file named "startup_funding2019.csv" obtained from OneDrive using the link https://azubiafrica-my.sharepoint.com/personal/teachops_azubiafrica_org/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fteachops%5Fazubiafrica%5Forg%2FDocuments%2FCareer%20Accelerator%20Data%5FSets%2FLP1%20Datasets&ga=1 
- The final dataset is a file with the name "startup_funding2018.csv" and was obtained from a Github Repository that can be accessed uusing this link https://github.com/Azubi-Africa/Career_Accelerator_LP1-Data_Analysis.

### Feature Description
Descrpition of the columns in the dataset: 

- Company/Brand: Name of the company/start-up
- Founded: Year start-up was established
- Headquarters/Location: Location where the start-up is headquartered
- Sector/Industry: The industry or sector in which the start-up operates, such as healthtech, fintech, etc.
- What it does/About Company: Brief overview of the company's function
- Founders: Founders of the Company
- Amount: Total amount raised by the start-up in each funding round
- Stage/Round: Details of the funding stages such as seed, series A, series B, etc.
- Investors: The names of the investors or investment firms involved

These are the useful variables that will provide the nexxesary data to answer our analytical business questions.


### Viewing the data
Here we will take a look into the data using different methods to gain an overall perspective of the data structure (number of columns and rows), the  number of columns and their data types and a sample of the dataframe (a preview of a few rows and columns)

In [57]:
# Read data from the CSV file 'startup_funding2020.csv' into a DataFrame named d21
d20 = pd.read_csv('startup_funding2020.csv')

# Display the first few rows of the DataFrame d20
d20.head()

,Company_Brand,Founded,HeadQuarter,Sector,What_it_does,Founders,Investor,Amount,Stage
0,Aqgromalin,2019.0,Chennai,AgriTech,Cultivating Ideas for Profit,"Prasanna Manogaran, Bharani C L",Angel investors,200000.0,NaN
1,Krayonnz,2019.0,Bangalore,EdTech,An academy-guardian-scholar centric ecosystem ...,"Saurabh Dixit, Gurudutt Upadhyay",GSF Accelerator,100000.0,Pre-seed
2,PadCare Labs,2018.0,Pune,Hygiene management,Converting bio-hazardous waste to harmless waste,Ajinkya Dhariya,Venture Center,NaN,Pre-seed
3,NCOME,2020.0,New Delhi,Escrow,Escrow-as-a-service platform,Ritesh Tiwari,"Venture Catalysts, PointOne Capital",400000.0,NaN
4,Gramophone,2016.0,Indore,AgriTech,Gramophone is an AgTech platform enabling acce...,"Ashish Rajan Singh, Harshit Gupta, Nishant Mah...","Siana Capital Management, Info Edge",340000.0,NaN

In [27]:
# Print information about the structure of the DataFrame d20
d20.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1055 entries, 0 to 1054
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Unnamed: 0     1055 non-null   int64
 1   Company_Brand  1055 non-null   object
 2   Founded        842 non-null    float64
 3   HeadQuarter    961 non-null    object
 4   Sector         1042 non-null   object
 5   What_it_does   1055 non-null   object
 6   Founders       1043 non-null   object
 7   Investor       1017 non-null   object
 8   Amount         801 non-null    float64
 9   Stage          591 non-null    object
 10  column10       2 non-null      object
dtypes: float64(2), int64(1), object(8)
memory usage: 90.8+ KB

In [29]:
# Display the shape of the DataFrame d20 (number of rows, number of columns)
d20.shape

(1055, 11)

In [37]:
# Generate summary statistics for the numerical columns in DataFrame d20 
num_stats = d20.describe().T

num_stats

,count,mean,std,min,25%,50%,75%,max
Unnamed: 0,1055.0,5.270000e+02,3.046966e+02,0.0,263.5,527.0,790.5,1.054000e+03
Founded,842.0,2.015363e+03,4.097909e+00,1973.0,2014.0,2016.0,2018.0,2.020000e+03
Amount,801.0,1.130430e+08,2.476635e+09,12700.0,1000000.0,3000000.0,11000000.0,7.000000e+10

In [39]:
# Generate descriptive statistics for the categorical columns in DataFrame d20
categorical_stats = d20.describe(include=['object']).T
categorical_stats

              count unique                               top freq
Company_Brand  1055    905                             Nykaa    6
HeadQuarter     961     77                         Bangalore  317
Sector         1042    302                           Fintech   80
What_it_does   1055    990  Provides online learning classes    4
Founders       1043    927                     Falguni Nayar    6
Investor       1017    848                 Venture Catalysts   20
Stage           591     42                          Series A   96
column10          2      2                          Pre-Seed    1

In [40]:
# Check for the total number of missing values in each column of the DataFrame d20
d20.isna().sum()

Unnamed: 0          0
Company_Brand       0
Founded           213
HeadQuarter        94
Sector             13
What_it_does        0
Founders           12
Investor           38
Amount            254
Stage             464
column10         1053
dtype: int64

In [42]:
# Check for duplicates in the d20 Dataframe
d20.duplicated().sum()

0

#### Data Quality Assessment
With respect to Data Quality Assessment, it is where the quality of the data is assessed, including completeness, accuracy, consistency and relevance. This is a crucial step in understanding the shortcomings of our data and being able to use that knwoledge to plan how to handle/clean the data.

The dataset "startup_funding2020" has 11 columns and 1055 rows but has no duplicate rows. The columns in the dataset are a mixture of strings/text (Company Brand, Sector, Headquarters, Founders, What it does, Investors, Stage, Column10), floats (Amount, Founded) and integers (Unnamed : 0). 

In this dataset, 3 columns had no missing values (Unnamed :0, Company Brand and What it does) with majority of the columns having less than 10% missing values (HeadQuarter, Sector, Founders, Investor). Only two other columns had over 25% missing values which were stage (43%) and Column10 (99.81%). 

It is instantly obvious the columns Unnamed :0 and column 10 have no relevance cause they possess no useful data with respect to our project goals. Other columns that would not be needed in reaching our goals (answering the analytical business questions) are Founded and What_It_Does.

[Back to Top](#Table-of-Contents)

### Data Cleaning
Messy data such as missing data and data in the wrong format can greatly impair our ability to analyze our data and gain useful insights from it. So at this stage, we clean the data so it can be useful in our analysis. 

#### Handling Missing Values
The unecessary columns are dropped from the dataset. For the two remaining columns with over 25% missing values (Stage and Amount), the rows that have missing values in both columns are also removed. The resulting dataframe is assessed for the new levels of missing data. For the columns wit less than 10% missing values, they are willed with either the median or mode.

In [46]:
#Viewing the missing values in each column of the dataframe d20
d20.isna().sum()

Unnamed: 0          0
Company_Brand       0
Founded           213
HeadQuarter        94
Sector             13
What_it_does        0
Founders           12
Investor           38
Amount            254
Stage             464
column10         1053
dtype: int64

In [65]:
#dropping the unecessary columns
d20.drop(columns=['column10', 'Unnamed: 0', 'Founded', 'What_it_does'], inplace= True)
d20

,Company_Brand,HeadQuarter,Sector,Founders,Investor,Amount,Stage
0,Aqgromalin,Chennai,AgriTech,"Prasanna Manogaran, Bharani C L",Angel investors,200000.0,NaN
1,Krayonnz,Bangalore,EdTech,"Saurabh Dixit, Gurudutt Upadhyay",GSF Accelerator,100000.0,Pre-seed
2,PadCare Labs,Pune,Hygiene management,Ajinkya Dhariya,Venture Center,NaN,Pre-seed
3,NCOME,New Delhi,Escrow,Ritesh Tiwari,"Venture Catalysts, PointOne Capital",400000.0,NaN
4,Gramophone,Indore,AgriTech,"Ashish Rajan Singh, Harshit Gupta, Nishant Mah...","Siana Capital Management, Info Edge",340000.0,NaN
...,...,...,...,...,...,...,...
1050,Leverage Edu,Delhi,Edtech,Akshay Chaturvedi,"DSG Consumer Partners, Blume Ventures",1500000.0,NaN
1051,EpiFi,NaN,Fintech,"Sujith Narayanan, Sumit Gwalani","Sequoia India, Ribbit Capital",13200000.0,Seed Round
1052,Purplle,Mumbai,Cosmetics,"Manish Taneja, Rahul Dash",Verlinvest,8000000.0,NaN
1053,Shuttl,Delhi,Transport,"Amit Singh, Deepanshu Malviya",SIG Global India Fund LLP.,8043000.0,Series C
1054,Pando,Chennai,Logitech,"Jayakrishnan, Abhijeet Manohar",Chiratae Ventures,9000000.0,Series A

In [66]:

# Filter rows where either the 'Amount' and 'Name' column has missing values
d31= d20[ d20['Amount'].isna() & d20['Stage'].isna()]
#d31.shape

# Checking the missing values for the new Dataframe d30
d31

,Company_Brand,HeadQuarter,Sector,Founders,Investor,Amount,Stage
12,MasterG,New Delhi,Fashion startup,Gayatri Jolly,Acumen Fund's angel programme,NaN,NaN
18,Pine Labs,Noida,FinTech,Amrish Rau,"Mastercard, Temasek Holdings",NaN,NaN
29,Delhivery,Gurgaon,E-commerce,"Kapil Bharati, Mohit Tandon, Sahil Barua, Sura...","Steadview Capital, Canada Pension Plan Investm...",NaN,NaN
40,Fleeca India,Jaipur,Tyre management,Tikam Jain,Bridgestone India,NaN,NaN
44,PointOne Capital,Bangalore,Venture capitalist,Mihir Jha,NaN,NaN,NaN
...,...,...,...,...,...,...,...
1021,IncubateHub,Bengaluru,Tech hub,Rajiv Mukherjee,Venture Catalysts,NaN,NaN
1022,Rage Coffee,Delhi,FMCG,Bharat Sethi,Refex Capital,NaN,NaN
1023,Skilancer,Noida,Technology,Neeraj Kumar,Venture Catalysts,NaN,NaN
1024,Harappa Education,New Delhi,Edtech,Pramath Raj Sinha,James Murdoch-led Lupa Systems,NaN,NaN
1028,PayMart,Chandigarh,Fintech,Amit Narang,"IIM Ahmedabad’s incubator (CIIE.CO),Chandigarh...",NaN,NaN

In [67]:
#dropping the missing rows for both Amount and Stage from the dataframe d20 and saving it as dataframe d20_Cleaned1
d20_cleaned1= d20.drop(index=d31.index)
d20_cleaned1

,Company_Brand,HeadQuarter,Sector,Founders,Investor,Amount,Stage
0,Aqgromalin,Chennai,AgriTech,"Prasanna Manogaran, Bharani C L",Angel investors,200000.0,NaN
1,Krayonnz,Bangalore,EdTech,"Saurabh Dixit, Gurudutt Upadhyay",GSF Accelerator,100000.0,Pre-seed
2,PadCare Labs,Pune,Hygiene management,Ajinkya Dhariya,Venture Center,NaN,Pre-seed
3,NCOME,New Delhi,Escrow,Ritesh Tiwari,"Venture Catalysts, PointOne Capital",400000.0,NaN
4,Gramophone,Indore,AgriTech,"Ashish Rajan Singh, Harshit Gupta, Nishant Mah...","Siana Capital Management, Info Edge",340000.0,NaN
...,...,...,...,...,...,...,...
1050,Leverage Edu,Delhi,Edtech,Akshay Chaturvedi,"DSG Consumer Partners, Blume Ventures",1500000.0,NaN
1051,EpiFi,NaN,Fintech,"Sujith Narayanan, Sumit Gwalani","Sequoia India, Ribbit Capital",13200000.0,Seed Round
1052,Purplle,Mumbai,Cosmetics,"Manish Taneja, Rahul Dash",Verlinvest,8000000.0,NaN
1053,Shuttl,Delhi,Transport,"Amit Singh, Deepanshu Malviya",SIG Global India Fund LLP.,8043000.0,Series C
1054,Pando,Chennai,Logitech,"Jayakrishnan, Abhijeet Manohar",Chiratae Ventures,9000000.0,Series A

In [70]:
#Checking the missing values in the new dataframe d20_cleaned1
d20_cleaned1.isna().sum()

Company_Brand      0
HeadQuarter       85
Sector            12
Founders          11
Investor          31
Amount           113
Stage            323
dtype: int64

In [75]:
# Impute missing values
d20_cleaned1['HeadQuarter'].fillna(d20_cleaned1['HeadQuarter'].mode()[0], inplace=True)
d20_cleaned1['Sector'].fillna(d20_cleaned1['Sector'].mode()[0], inplace=True)
d20_cleaned1['Founders'].fillna('Unknown', inplace=True)
d20_cleaned1['Investor'].fillna('Unknown', inplace=True)
d20_cleaned1['Amount'].fillna(d20_cleaned1['Amount'].median(), inplace=True)
d20_cleaned1['Stage'].fillna('Unknown', inplace=True)

,Company_Brand,HeadQuarter,Sector,Founders,Investor,Amount,Stage
21,SucSEED Indovation,Hyderabad,FinTech,Vikrant Varshney,NaN,5000000.0,NaN
24,Circle of Angels,Gurgaon,FinTech,Karanpal Singh,NaN,3000000.0,NaN
151,BlackSoil,Mumbai,FinTech,Ankur Bansal,NaN,10000000.0,NaN
241,SoOLEGAL,New Delhi,LegalTech,Manish Kaul,NaN,4000000.0,NaN
262,Phononic Vibes,"Milano, Lombardia, Italy",Deeptech,"Andrea Boeri, Braghin Francesco, Giovanni Cape...",NaN,2300000.0,NaN
274,Antaios,France,Tech company,Jean Pierre Nozieres,NaN,11000000.0,NaN
305,Sapio Analytics,Mumbai,Tech company,"Ashwin Srivastava, Hardik Somani",NaN,150000.0,NaN
318,GenieTalk,Indore,Tech company,"Santosh Kataria, Ankit Kimtee, Vivek Jain",NaN,750000.0,NaN
325,BestDoc,Kochi,HealthCare,"Afsal Salu, Fayaz Bin Abdu, Soudabi",NaN,2100000.0,NaN
329,Inflexor Ventures,Mumbai,FinTech,"Parampara Capital, Venkat Vallabhaneni, Jatin ...",NaN,10000000.0,NaN
335,SignalX,Hyderabad,SaaS platform,Govind Balachandran,NaN,750000.0,NaN
337,Vesta Space Technology,Pune,Tech Startup,Arun Kumar Sureban,NaN,10000000.0,NaN
338,Dozee,Bangalore,HealthTech,Gaurav Parchani,NaN,1600000.0,NaN
346,3one4 Capital,Bangalore,Venture capital,"Pranav Pai, Siddarth Pai",NaN,100000000.0,NaN
365,QShala,Bangalore,EdTech,"Sachin Ravi, Raghav Chakravarthy",NaN,300000.0,NaN

In [76]:
# Impute missing values
d20_cleaned1['HeadQuarter'].fillna(d20_cleaned1['HeadQuarter'].mode()[0], inplace=True)
d20_cleaned1['Sector'].fillna(d20_cleaned1['Sector'].mode()[0], inplace=True)
d20_cleaned1['Founders'].fillna('Unknown', inplace=True)
d20_cleaned1['Investor'].fillna('Unknown', inplace=True)
d20_cleaned1['Amount'].fillna(d20_cleaned1['Amount'].median(), inplace=True)
d20_cleaned1['Stage'].fillna('Unknown', inplace=True)

In [77]:
#CVerifying that there are no missing values after the imputation process
d20_cleaned1.isna().sum()

Company_Brand    0
HeadQuarter      0
Sector           0
Founders         0
Investor         0
Amount           0
Stage            0
dtype: int64

### Restructuring Data
After taking care of the missing values, there is still work to be done to make the dataset presentable and usable. This include renaming of columns to ensure that when merging with the other dataset, we havve identical column headers. Also, a column named Year will be added to be able to distinguish between rows from different dataset year when the merging occurs.

In [80]:
#Renaming the columns in the DataFrame d20_cleaned1
d20_cleaned1.rename(columns={'Company_Brand' : 'Company_Name'}, inplace=True)
d20_cleaned1.rename(columns={'HeadQuarter' : 'Location'}, inplace=True)
d20_cleaned1.rename(columns={'Sector' : 'Industry'}, inplace=True)
d20_cleaned1.rename(columns={'Stage' : 'Funding_Stage'}, inplace=True)

In [81]:
#Adding a colomn named 'Year' to the dataframe d20_cleaned1
d20_cleaned1['Year']= 2020
d20_cleaned1

,Company_Name,Location,Industry,Founders,Investor,Amount,Funding_Stage,Year
0,Aqgromalin,Chennai,AgriTech,"Prasanna Manogaran, Bharani C L",Angel investors,200000.0,Unknown,2020
1,Krayonnz,Bangalore,EdTech,"Saurabh Dixit, Gurudutt Upadhyay",GSF Accelerator,100000.0,Pre-seed,2020
2,PadCare Labs,Pune,Hygiene management,Ajinkya Dhariya,Venture Center,3000000.0,Pre-seed,2020
3,NCOME,New Delhi,Escrow,Ritesh Tiwari,"Venture Catalysts, PointOne Capital",400000.0,Unknown,2020
4,Gramophone,Indore,AgriTech,"Ashish Rajan Singh, Harshit Gupta, Nishant Mah...","Siana Capital Management, Info Edge",340000.0,Unknown,2020
...,...,...,...,...,...,...,...,...
1050,Leverage Edu,Delhi,Edtech,Akshay Chaturvedi,"DSG Consumer Partners, Blume Ventures",1500000.0,Unknown,2020
1051,EpiFi,Bangalore,Fintech,"Sujith Narayanan, Sumit Gwalani","Sequoia India, Ribbit Capital",13200000.0,Seed Round,2020
1052,Purplle,Mumbai,Cosmetics,"Manish Taneja, Rahul Dash",Verlinvest,8000000.0,Unknown,2020
1053,Shuttl,Delhi,Transport,"Amit Singh, Deepanshu Malviya",SIG Global India Fund LLP.,8043000.0,Series C,2020
1054,Pando,Chennai,Logitech,"Jayakrishnan, Abhijeet Manohar",Chiratae Ventures,9000000.0,Series A,2020

In [82]:
#Viewing a summary on d20_cleaned1 to ensure that the columns have the desired datatypes
d20_cleaned1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 914 entries, 0 to 1054
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Company_Name   914 non-null    object
 1   Location       914 non-null    object
 2   Industry       914 non-null    object
 3   Founders       914 non-null    object
 4   Investor       914 non-null    object
 5   Amount         914 non-null    float64
 6   Funding_Stage  914 non-null    object
 7   Year           914 non-null    int64
dtypes: float64(1), int64(1), object(6)
memory usage: 64.3+ KB

### Handling Outliers
The presence of outliers can skew th eresults of our statisical analyses and as such we need to identify and handle/manage them. In this section, we study the presence of outliers in the Amount column of our dataset.

In [85]:
#Calculate the First and Third Quartiles (Q1 and Q3):
Q1 = d20_cleaned1['Amount'].quantile(0.25)
Q3 = d20_cleaned1['Amount'].quantile(0.75)

#Calculate the Interquartile Range (IQR)
IQR = Q3 - Q1

# Identify outliers
outliers = d20_cleaned1[((d20_cleaned1['Amount'] < (Q1 - 1.5 * IQR)) | (d20_cleaned1['Amount'] > (Q3 + 1.5 * IQR)))]
outliers

,Company_Name,Location,Industry,Founders,Investor,Amount,Funding_Stage,Year
8,Rupeek,Bangalore,FinTech,"Amar Prabhu, Ashwin Soni, Sumit Maniyar","KB Investment, Bertelsmann India Investments",45000000.0,Series C,2020
15,Zomato,Gurgaon,Food Delivery,"Deepinder Goyal, Gaurav Gupta, Pankaj Chaddah","Kora, Tiger Global Management",660000000.0,Unknown,2020
26,Glance,Bangalore,AI startup,Naveen Tewari,Mithril Capital Management.,145000000.0,Unknown,2020
27,VerSe Innovation,Bangalore,Telecommunication,Virendra Gupta,Google,100000000.0,Unknown,2020
45,Ayana,Bangalore,Renewable player,Shivanand N,"NIIF Ltd, CDC Group",390000000.0,Unknown,2020
...,...,...,...,...,...,...,...,...
1009,Bounce,Bangalore,Automotive and Rentals,"Vivekananda Hallekere, Anil Giri Raju,Arun Agni","Accel Partners, B Capital",97500000.0,Series D,2020
1010,Zinier,Bangalore,Automation,Arka Dhar,ICONIQ Capital,90000000.0,Series C,2020
1034,Zomato,Bangalore,Foodtech,Deepinder Goyal,Ant Financial,150000000.0,Unknown,2020
1035,Byju,Bangalore,Edtech,Byju Raveendran,Tiger Global,200000000.0,Unknown,2020
1037,HighRadius,Hyderabad,SaaS,Sashi Narahari,ICONIQ Capital,125000000.0,Series B,2020

In [89]:
ods=  outliers[outliers["Funding_Stage"] == 'Unknown']
ods.info()

<class 'pandas.core.frame.DataFrame'>
Index: 58 entries, 15 to 1035
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Company_Name   58 non-null     object
 1   Location       58 non-null     object
 2   Industry       58 non-null     object
 3   Founders       58 non-null     object
 4   Investor       58 non-null     object
 5   Amount         58 non-null     float64
 6   Funding_Stage  58 non-null     object
 7   Year           58 non-null     int64
dtypes: float64(1), int64(1), object(6)
memory usage: 4.1+ KB

#### Conclusion on Outliers
There are 131 rows in the Amount column that were outliers. Out of the 131, 58 of them had an Unknwon funding stage. Initially, the thought was to remove that subset (outliers that have missing/unknwown Funding Stage) but that would affect other columns such as Locaton as a majority (25) of this subset were located at Bangalore and thus removing these outliers could affect the data.

### String Data Cleaning

For some of the entries in our data, they may be in the wrong format or would have wrong characters added to them that can cause issues when we are handling and manipulating the data thus it is necessary to correct any noise (messy/incorrect string text). This will ensure consistencyy an accuracy as we perform our analysis.

In [96]:
#Listing all the unique values in the Location column
d20_cleaned1['Location'].unique()

array(['Chennai', 'Bangalore', 'Pune', 'New Delhi', 'Indore', 'Hyderabad',
       'Gurgaon', 'Belgaum', 'Mumbai', 'Noida', 'Andheri', 'Ahmedabad',
       'Jaipur', 'Kolkata', 'Tirunelveli, Tamilnadu', 'Thane',
       'Singapore', 'Gurugram', 'Gujarat', 'Haryana', 'Jodhpur',
       'Jaipur, Rajastan', 'Delhi', 'California', 'Dhingsara, Haryana',
       'New York, United States',
       'San Francisco, California, United States',
       'San Francisco, United States', 'San Ramon, California',
       'Paris, Ile-de-France, France', 'Plano, Texas, United States',
       'Sydney', 'San Francisco Bay Area, Silicon Valley, West Coast',
       'Bangaldesh', 'London, England, United Kingdom',
       'Sydney, New South Wales, Australia', 'Milano, Lombardia, Italy',
       'France', 'San Francisco Bay Area, West Coast, Western US',
       'Trivandrum, Kerala, India', 'Cochin', 'Samastipur, Bihar',
       'Irvine, California, United States', 'Tumkur, Karnataka',
       'Newcastle Upon Tyne, Newcastle upon Tyne, United Kingdom',
       'Shanghai, China', 'Jiaxing, Zhejiang, China', 'Rajastan', 'Kochi',
       'Ludhiana', 'Dehradun', 'San Francisco',
       'Tangerang, Jawa Barat, Indonesia', 'Berlin', 'Seattle', 'Riyadh',
       'Seoul', 'New York', 'Bangkok', 'Kanpur', 'Chandigarh',
       'Hyderebad', 'Odisha', 'Bihar', 'Goa', 'Uttar Pradesh', 'Banglore',
       'Coimbatore'], dtype=object)

In [108]:
#Creating a variable for the list of incorrect locations
wrong_location = ['Singapore', 'California',
'San Ramon, California', 'Paris, Ile-de-France, France', 'Plano, Texas, United States',
'Sydney', 'San Francisco Bay Area, Silicon Valley, West Coast', 'Bangladesh',
'London, England, United Kingdom', 'Sydney, New South Wales, Australia',
'Milano, Lombardia, Italy', 'France', 'San Francisco Bay Area, West Coast, Western US',
'Irvine, California, United States', 'Newcastle Upon Tyne, Newcastle upon Tyne, United Kingdom',
'Shanghai, China', 'Jiaxing, Zhejiang, China', 'San Francisco',
'Tangerang, Jawa Barat, Indonesia', 'Berlin', 'Seattle', 'Riyadh', 'Seoul', 'New York',
'Bangkok','New York, United States',  'San Francisco, California, United States', 'San Francisco, United States', 'Bangaldesh']

#display rows in d20cleaned1 that have startups not from India
d20_cleaned1[d20_cleaned1['Location'].isin(wrong_location)]

,Company_Name,Location,Industry,Founders,Investor,Amount,Funding_Stage,Year
91,Kyt,Singapore,EdTech,"Bhavik Rathod, Tripti Ahuja",Sequoia Capital India’s Surge,2.500000e+06,Unknown,2020
176,Udacity,California,EdTech,"David Stavens, Mike Sokolsky, Sebastian Thrun","Hercules Capital, Inc.Bertelsmann",7.500000e+07,Debt,2020
186,Leena AI,"New York, United States",AI startup,"Adit Jain, Anand Prajapati, Mayank Goyal","Alan Patricof, Jim Moffatt",8.000000e+06,Unknown,2020
223,Hubilo,"San Francisco, California, United States",Tech company,"Mayank Agarwal, Vaibhav Jain","Nishant Rao, Jonathan Boutelle",4.500000e+06,Seed,2020
225,Ketos,"San Francisco, United States",AI startup,Meena Sankaran,"Citi Ventures, Illuminated Funds Group",1.800000e+07,Unknown,2020
229,Tekion,"San Ramon, California",AI startup,"Guru Sankararaman, Jay Vijayan","Alliance Ventures, Storm Ventures",1.500000e+08,Series C,2020
230,Brighteye Ventures,"Paris, Ile-de-France, France",Edtech,David guerin,Tandem,5.400000e+06,Unknown,2020
232,VitalTech,"Plano, Texas, United States",HeathTech,Anjan Panneer Selvam,Tech Mahindra,3.000000e+06,Seed,2020
239,Tiliter,Sydney,Retail,"Chris Sampson, Marcel Herz, Martin Karafilis","AngelList, Investec",7.500000e+06,Unknown,2020
240,Slintel,"San Francisco Bay Area, Silicon Valley, West C...",Sles and marketing,"Deepak Anchala, Rahul Bhattacharya, Ranjana TN","Accel, Stellaris Venture Partners",4.200000e+06,Unknown,2020
245,ShopUp,Bangaldesh,E-commerce,"Afeef Zaman, Ataur Rahim Chowdhury, Siffat Sarwar","Flourish Ventures, Lonsdale Capital",2.200000e+07,Series A,2020
260,Arrival,"London, England, United Kingdom",EV startup,Denis Sverdlov,"UPS Ventures, Hyundai Motor Company",1.180000e+08,Unknown,2020
261,Cover Genius,"Sydney, New South Wales, Australia",FinTech,"Angus McDonald, Chris Bayley","King River Capital, Leap Capital",1.500000e+07,Unknown,2020
262,Phononic Vibes,"Milano, Lombardia, Italy",Deeptech,"Andrea Boeri, Braghin Francesco, Giovanni Cape...",Unknown,2.300000e+06,Unknown,2020
264,Clair,"New York, United States",FinTech,"Alex Kostecki, Erich Nussbaumer, Nico Simko","Upfront Ventures, Walkabout Ventures",4.500000e+06,Seed,2020
273,Your MD,"London, England, United Kingdom",Healthcare,"Alessandro Traverso, Birger Lie, Harald Jellum...","Orkla Ventures, Smedvig Capital",2.500000e+07,Unknown,2020
274,Antaios,France,Tech company,Jean Pierre Nozieres,Unknown,1.100000e+07,Unknown,2020
279,Chargebee,"San Francisco Bay Area, West Coast, Western US",SaaS startup,"KP Saravanan, Krish Subramanian, Rajaraman San...","Accel, Steadview Capital",5.500000e+07,Series F,2020
287,Monet Networks,"Irvine, California, United States",AI startup,Anurag Bist,"SenseAI Ventures, EvoNexus",5.000000e+05,Bridge,2020
292,Omnify,"San Francisco Bay Area, Silicon Valley, West C...",SaaS startup,"Kabandi Saika, Manik Mehta","Saurabh Arora, LD Sharma",3.000000e+06,Pre-series A,2020
300,Coralogix,"San Francisco, California, United States",SaaS startup,"Ariel Assaraf, Guy Kroupp, Lior Redlus, Yoni F...","2B Angels, Janvest Capital Partners",2.500000e+07,Series B,2020
301,Equiwatt,"Newcastle Upon Tyne, Newcastle upon Tyne, Unit...",Tech company,"Johnson Fernandes, Ravneet Kaur",Rising Stars,3.000000e+05,Unknown,2020
303,Zhangmen,"Shanghai, China",Edtech,Yi Zhang,"CICC Alpha, VMS Asset Management",4.000000e+08,Unknown,2020
306,Taimei,"Jiaxing, Zhejiang, China",HealthCare,Lu Zhao,"Cowin Venture, ZSVC",1.760000e+08,Unknown,2020
317,Snowflake,California,Tech company,"Benoit Dageville, Bob Muglia, Marcin Zukowski,...","Salesforce Ventures, Dragoneer Investment Group",3.000000e+09,Unknown,2020
373,SquadStack,San Francisco,Tech company,"Apurv Agrawal, Kanika Jain, Rishabh Ladha, Vik...","Chiratae Ventures, Blume Ventures",5.000000e+06,Series A,2020
384,Yummy Corp,"Tangerang, Jawa Barat, Indonesia",Food Industry,Mario Suntanu,"Palm Drive Capital, Amatil X Ventures",1.200000e+07,Series B,2020
386,Clairvolex,California,Tech Startup,Manoj Pillai,"JF Mauritius SPV, IndusAge Partners",2.000000e+06,Debt,2020
388,Brinton,California,HealthTech,Rahul Darda,"India Alternatives Private Equity Fund, Tata C...",1.300000e+06,Debt,2020
390,Infarm,Berlin,AgriTech,"Erez Galonska, Guy Galonska, Osnat Michaeli","Bonnier Ventures, Hanaco Venture Capital",1.700000e+08,Series C,2020
391,Zuper,Seattle,SaaS startup,Vijay Narasiman,"Gemba Capital, Gunderson Dettmer",1.100000e+06,Seed,2020
397,Penny,Riyadh,SaaS startup,"Iyad Aldalooj, Majid Aldalooj, Mohammed Ibrahim",Unknown,1.300000e+06,Seed,2020
399,Precily,California,SaaS startup,Bharath Rao,"Windrose Capital, Anil Advani",3.000000e+06,Seed,2020
400,SmartClean,Singapore,Tech Startup,"Abhishek Mishra, Kush Agarwal, Lav Agarwal, St...","Seeds Capital, AIM Smart City",3.400000e+06,Pre- series A,2020
413,DillyHub,Seoul,Publication,Ji Cheol Ryu,"Kakao Ventures, Shinhan Capital",1.400000e+06,Seed,2020
420,Observe ai,San Francisco,Tech,"Akash Singh, Sharath Keshava Narayana, Swapnil...","01 Advisors, Steadview Capital",5.400000e+07,Series B,2020
456,Hippo Video,New York,Video personalization,Karthi Mariappan,"Surge, Kae Capital",4.000000e+06,Series A,2020
457,Hasura,San Francisco,Software Company,"Tanmai Gopal, Rajoshi Ghosh","Nexus Venture Partners, Sam Lambert",2.500000e+07,Series B,2020
458,Qapita,Singapore,FinTech,"Ravi Ravulaparthi, Lakshman Gupta, Vamsee Mohan","Alto Partners, Mission Holdings",1.080000e+06,Seed,2020
459,Sunday,Bangkok,FinTech,Cindy Kua,"SCB 10X, LINE Ventures",9.000000e+06,Pre-Series B,2020
483,CredoLab,Singapore,Tech,Peter Barcak,"GB Group, Walden International",7.000000e+06,Series A,2020

In [109]:
# Creating a mask to isolate the rows with correct locations
mask = ~d20_cleaned1['Location'].isin(wrong_location)

# Removing rows where startups are not located in India and creating a new DataFrame d20_cleaned2
d20_cleaned2 = d20_cleaned1[mask]


d20_cleaned2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 873 entries, 0 to 1054
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Company_Name   873 non-null    object
 1   Location       873 non-null    object
 2   Industry       873 non-null    object
 3   Founders       873 non-null    object
 4   Investor       873 non-null    object
 5   Amount         873 non-null    float64
 6   Funding_Stage  873 non-null    object
 7   Year           873 non-null    int64
dtypes: float64(1), int64(1), object(6)
memory usage: 61.4+ KB

In [110]:
#Listing the unique locations after removing startups not in India
d20_cleaned2['Location'].unique()

array(['Chennai', 'Bangalore', 'Pune', 'New Delhi', 'Indore', 'Hyderabad',
       'Gurgaon', 'Belgaum', 'Mumbai', 'Noida', 'Andheri', 'Ahmedabad',
       'Jaipur', 'Kolkata', 'Tirunelveli, Tamilnadu', 'Thane', 'Gurugram',
       'Gujarat', 'Haryana', 'Jodhpur', 'Jaipur, Rajastan', 'Delhi',
       'Dhingsara, Haryana', 'Trivandrum, Kerala, India', 'Cochin',
       'Samastipur, Bihar', 'Tumkur, Karnataka', 'Rajastan', 'Kochi',
       'Ludhiana', 'Dehradun', 'Kanpur', 'Chandigarh', 'Hyderebad',
       'Odisha', 'Bihar', 'Goa', 'Uttar Pradesh', 'Banglore',
       'Coimbatore'], dtype=object)

In [112]:
#replacing locations with multiple names with a common name for consistency
replacements = {
    'Banglore': 'Bangalore',
    'Gurugram': 'Gurgaon',
    'Jaipur, Rajastan': 'Jaipur',
    'Cochin': 'Kochi'
}
d20_cleaned2.replace(replacements, inplace=True)


#Listing the unique locations to verify the replacement were successful
d20_cleaned2['Location'].unique()

array(['Chennai', 'Bangalore', 'Pune', 'New Delhi', 'Indore', 'Hyderabad',
       'Gurgaon', 'Belgaum', 'Mumbai', 'Noida', 'Andheri', 'Ahmedabad',
       'Jaipur', 'Kolkata', 'Tirunelveli, Tamilnadu', 'Thane', 'Gujarat',
       'Haryana', 'Jodhpur', 'Delhi', 'Dhingsara, Haryana',
       'Trivandrum, Kerala, India', 'Kochi', 'Samastipur, Bihar',
       'Tumkur, Karnataka', 'Rajastan', 'Ludhiana', 'Dehradun', 'Kanpur',
       'Chandigarh', 'Hyderebad', 'Odisha', 'Bihar', 'Goa',
       'Uttar Pradesh', 'Coimbatore'], dtype=object)